# Generated by Django 5.1.7 on 2025-06-24 18:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suiv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anneeacademique',
            options={'ordering': ['-annee'], 'verbose_name': 'Année académique', 'verbose_name_plural': 'Années académiques'},
        ),
        migrations.AlterModelOptions(
            name='groupeetudiant',
            options={'ordering': ['annee_academique', 'niveau', 'parcours', 'nom_groupe'], 'verbose_name': "Groupe d'étudiants", 'verbose_name_plural': "Groupes d'étudiants"},
        ),
        migrations.RemoveConstraint(
            model_name='groupeetudiant',
            name='unique_groupe_niveau_parcours',
        ),
        migrations.RemoveField(
            model_name='anneeacademique',
            name='enseignants',
        ),
        migrations.RemoveField(
            model_name='anneeacademique',
            name='suivis',
        ),
        migrations.AddField(
            model_name='anneeacademique',
            name='date_debut',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de début'),
        ),
        migrations.AddField(
            model_name='anneeacademique',
            name='date_fin',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='anneeacademique',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='anneeacademique',
            name='est_active',
            field=models.BooleanField(default=False, verbose_name='Année active'),
        ),
        migrations.AddField(
            model_name='groupeetudiant',
            name='annee_academique',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Suiv.anneeacademique', verbose_name='Année académique'),
        ),
        migrations.AddField(
            model_name='groupeetudiant',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='groupeetudiant',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='groupeetudiant',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Groupe actif'),
        ),
        migrations.AddField(
            model_name='suivienseignement',
            name='date_emargement',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de l'émargement"),
        ),
        migrations.AddField(
            model_name='suivienseignement',
            name='delegue_contact',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact du délégué'),
        ),
        migrations.AddField(
            model_name='suivienseignement',
            name='delegue_nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du délégué'),
        ),
        migrations.AddField(
            model_name='suivienseignement',
            name='motif_delegation',
            field=models.TextField(blank=True, null=True, verbose_name='Motif de la délégation'),
        ),
        migrations.AlterField(
            model_name='anneeacademique',
            name='annee',
            field=models.CharField(max_length=10, unique=True, verbose_name='Année académique'),
        ),
        migrations.AlterField(
            model_name='suivienseignement',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Suiv.anneeacademique', verbose_name='Année académique'),
        ),
        migrations.AddConstraint(
            model_name='groupeetudiant',
            constraint=models.UniqueConstraint(fields=('nom_groupe', 'niveau', 'parcours', 'annee_academique'), name='unique_groupe_niveau_parcours_annee'),
        ),
    ]
