# Generated by Django 5.1.7 on 2025-03-13 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suiv', '0002_auto_20250309_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suivienseignement',
            name='emargement_enseignant',
        ),
        migrations.RemoveField(
            model_name='suivienseignement',
            name='nb_groupes',
        ),
        migrations.AlterField(
            model_name='suivienseignement',
            name='heures_cm',
            field=models.FloatField(default=0, verbose_name="Nombre d'heures CM"),
        ),
        migrations.AlterField(
            model_name='suivienseignement',
            name='heures_td',
            field=models.FloatField(default=0, verbose_name="Nombre d'heures TD"),
        ),
        migrations.AlterField(
            model_name='suivienseignement',
            name='heures_tp',
            field=models.FloatField(default=0, verbose_name="Nombre d'heures TP"),
        ),
        migrations.CreateModel(
            name='GroupeEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_groupe', models.CharField(max_length=100, verbose_name='Nom du groupe')),
                ('parcours', models.CharField(max_length=255, verbose_name='Parcours')),
                ('effectif', models.PositiveIntegerField(default=0, verbose_name='Effectif')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Suiv.niveauetude', verbose_name="Niveau d'étude")),
            ],
            options={
                'verbose_name': "Groupe d'étudiants",
                'verbose_name_plural': "Groupes d'étudiants",
                'unique_together': {('nom_groupe', 'niveau')},
            },
        ),
        migrations.AddField(
            model_name='suivienseignement',
            name='groupes',
            field=models.ManyToManyField(blank=True, default=0, related_name='suivis', to='Suiv.groupeetudiant', verbose_name="Groupes d'étudiants"),
        ),
    ]
