# Generated by Django 5.1.7 on 2025-06-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suiv', '0002_alter_anneeacademique_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupeetudiant',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
    ]
