# Generated by Django 5.1.7 on 2025-03-13 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suiv', '0003_remove_suivienseignement_emargement_enseignant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='enseignants',
            field=models.ManyToManyField(related_name='assigned_cours', related_query_name='assigned_cours', to='Suiv.enseigner'),
        ),
        migrations.AlterField(
            model_name='enseigner',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignants_cours', to='Suiv.cours', verbose_name='Cours'),
        ),
    ]
