# Generated by Django 5.1.7 on 2025-03-13 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suiv', '0004_cours_enseignants_alter_enseigner_cours'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupeetudiant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cours',
            name='enseignants',
            field=models.ManyToManyField(blank=True, related_name='assigned_cours', related_query_name='assigned_cours', to='Suiv.enseigner'),
        ),
        migrations.AlterField(
            model_name='groupeetudiant',
            name='parcours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_etudiants', to='Suiv.cours', verbose_name='Parcours'),
        ),
        migrations.AlterField(
            model_name='suivienseignement',
            name='annee_academique',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='Suiv.anneeacademique', verbose_name='Année académique'),
        ),
        migrations.AlterField(
            model_name='suivienseignement',
            name='enseignant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='Suiv.enseignant', verbose_name='Enseignant'),
        ),
        migrations.AddConstraint(
            model_name='groupeetudiant',
            constraint=models.UniqueConstraint(fields=('nom_groupe', 'niveau', 'parcours'), name='unique_groupe_niveau_parcours'),
        ),
    ]
