# Generated by Django 5.1.7 on 2025-03-13 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suiv', '0005_alter_groupeetudiant_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupeetudiant',
            name='effectif',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Effectif'),
        ),
        migrations.AlterField(
            model_name='groupeetudiant',
            name='parcours',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupes_etudiants', to='Suiv.cours', verbose_name='Parcours'),
        ),
    ]
