# Generated by Django 5.1.7 on 2025-03-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suiv', '0006_alter_groupeetudiant_effectif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneeacademique',
            name='annee',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='suivienseignement',
            name='annee_academique',
            field=models.CharField(default='2025', max_length=10, verbose_name='Année académique'),
        ),
    ]
