# Generated by Django 5.1.7 on 2025-03-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suiv', '0007_alter_anneeacademique_annee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivienseignement',
            name='annee_academique',
            field=models.CharField(default='2025', max_length=4),
        ),
    ]
