# Generated by Django 5.1.7 on 2025-03-13 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Suiv', '0008_alter_suivienseignement_annee_academique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anneeacademique',
            options={},
        ),
    ]
