# Generated by Django 5.1.7 on 2025-03-13 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Suiv', '0009_alter_anneeacademique_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='annee_academique',
        ),
    ]
