# Generated by Django 5.1.7 on 2025-03-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suiv', '0010_remove_enseignant_annee_academique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneeacademique',
            name='annee',
            field=models.IntegerField(max_length=10),
        ),
    ]
