# Generated by Django 5.1.7 on 2025-03-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suiv', '0011_alter_anneeacademique_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneeacademique',
            name='annee',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='suivienseignement',
            name='groupes',
            field=models.ManyToManyField(blank=True, related_name='suivis', to='Suiv.groupeetudiant', verbose_name="Groupes d'étudiants"),
        ),
    ]
