# Generated by Django 5.1.7 on 2025-03-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suiv', '0012_alter_anneeacademique_annee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anneeacademique',
            options={'verbose_name': 'Année académique', 'verbose_name_plural': 'Années académiques'},
        ),
        migrations.RemoveField(
            model_name='cours',
            name='enseignants',
        ),
        migrations.AlterField(
            model_name='groupeetudiant',
            name='parcours',
            field=models.CharField(max_length=255, verbose_name='Parcours'),
        ),
    ]
