# Generated by Django 5.1.7 on 2025-03-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suiv', '0013_alter_anneeacademique_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneeacademique',
            name='enseignants',
            field=models.ManyToManyField(blank=True, related_name='annees_academiques', to='Suiv.enseignant'),
        ),
    ]
