# Generated by Django 5.1.7 on 2025-03-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suiv', '0014_anneeacademique_enseignants'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneeacademique',
            name='suivis',
            field=models.ManyToManyField(blank=True, related_name='annees_academiques', to='Suiv.suivienseignement'),
        ),
    ]
