# Generated by Django 5.1.7 on 2025-03-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suiv', '0015_anneeacademique_suivis'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='cours',
            field=models.ManyToManyField(blank=True, related_name='enseignants', to='Suiv.cours'),
        ),
    ]
